### PR TITLE
Restore unmodified code in parameters cell

### LINKED ISSUE #17: Mysterious behaviour on unrecognised code in parameters cell
cc @philsmt @cydanil @RobertRosca @tmichela @D4vidH4mm3r from today's debugging session.

I realised today how baffling it is when nbparameterise doesn't recognise something like `chunk_shape = (5, 100, 100)` (a tuple) or `kwargs = dict(parallel=False)` (a dictionary defined with a function call). `extract_parameters` silently ignores them (see also #7), and then `replace_definitions` builds the new assignment code without them, so variables you expect to use are never defined. To make matters worse, `parameter_values` ignores any keyword arguments it's given that don't match a recognised parameter :facepalm: .

What can we do?

- The obvious thought is to error/warn when the parameters cell contains code that's not recognised as a parameter assignment. This would at least make it more obvious what's happening, but may be annoying/broken for some use cases that currently work (like defining a `balance_sequences` function in the parameter cell for separate introspection).
- We could recognise more things. The idea for now is to recognise the types that go in JSON, but tuples are mostly like lists, and `dict()` calls are almost certainly equivalent to dict literals. This would go some way to make life easier, but there are pretty obvious cases which get more complicated, like sets or f-strings.
- Python 3.9 introduces `ast.unparse()`, which we could use to recreate any unrecognised code rather than just blowing it away. Does keeping the order matter if it's interleaved with parameters? I think we can put all the parameter assignments first, and any other code below, because assigning literals to variables shouldn't depend on anything else.

We should also have an equivalent of `parameter_values` which complains about unrecognised input values, rather than ignoring them. I've been thinking of making an interface for a dict of parameters rather than a list (now that dicts preserve order), so this might be the opportunity to redesign other things.

### PR DESCRIPTION
**Pull request by takluyver**
This uses `ast.unparse()` on Python 3.9, and the [astunparse backport](https://pypi.org/project/astunparse/) on older versions, to recreate any code in the parameters cell not recognised as parameter definitions.

The AST doesn't preserve comments or formatting, so these will be lost, but the code should still do the same thing. Any code that's not treated as parameters will be moved after the parameter definitions, which might change its behaviour in some rare cases, but hopefully not many.

While I was working on this, I also enabled:

- Recognising annotated assignments (`a: int = 7`) as parameters. The annotation is ignored for now - this is just like `a = 7`.
- Work with a dict of parameters by name, rather than a list. More convenient for checking e.g. 'does parameter x exist'.

Closes #17.

cc @philsmt - we had a discussion about this.

### CODE REVIEW

**Comment by takluyver** [comment]
Thinking some more about it, I realised that it would be easy enough to keep the recreated code in its original order, replacing each assignment in place. However, that highlights a couple of corner cases that so far haven't had much thought:

1. If the same name is defined more than once (`a = 1; a = 2`) and we want to set a to 3, do we replace both? Only the last one? Or should it be an error when extracting parameters? At present, the list-based APIs will extract two separate parameters with name 'a', and `parameter_values()` will change the value of both of them.
2. Is it OK to add parameters for names which aren't in the notebook to start with? At present, `replace_definitions()` is fine with this, but `parameter_values()` will silently ignore any names which don't correspond to an existing parameter (a behaviour which is definitely wrong).

:thinking:

**Comment by takluyver** [comment]
From Python 3.8, we could possibly even do something cleverer, using the character positions of the nodes to replace just those pieces, leaving the rest of the code untouched. That would be cool, but it's not my priority today.

**Comment by sam2332** [comment]
Wow this looks great

**Comment by takluyver** [comment]
I've now gone for supporting Python 3.8+ only, and preserving the surrounding code when replacing assignments with new parameter values.

With regard to my questions from [this comment](https://github.com/takluyver/nbparameterise/pull/19#issuecomment-874662095):

1. Duplicate names will be allowed, and setting a new value will replace all of them. I hope this is a corner case rare enough that we don't need to do anything special for it.
2. Adding new parameter names will still work - the assignments will be added to the bottom of the parameter cell. `parameter_values()` still ignores new names by default - I realised we were actually relying on this at EuXFEL - but you can pass `new='add'` or `new='error'` to change this. You can also give the new values in a dict instead of keyword args - if you have a parameter called `new`, you'll need to use this.

And one that I didn't ask:

4. It will no longer be possible to *delete* assignments from the parameter cell. In 0.5, you can remove some of the parameters from the list you pass to `replace_definitions()`, and the new parameter cell won't have those assignments. With these changes, they'll keep whatever they were assigned before.

**Comment by takluyver** [comment]
OK, I'm fairly happy with this now. I'll probably merge it on Monday unless anyone spots a major problem before then. Then I'll get back to other pull requests - sorry it has taken so long.

**Pull request merged**
