### PR TITLE
Missing language override in replace_definitions()

### PR DESCRIPTION
**Pull request by IrekRybark**
It seems to me that parameter override=lang is missing while calling get_driver_module() in replace_definitions().

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, I think you're right :-)

**Comment by IrekRybark** [comment]
Thomas,
Thanks a bunch for the code.
I found it very useful.

The only thing, which I needed to take care of was the cell calculation
timeout setting.
Not sure what would be the right approach but had to call preprocess()
explicitly.

    new_nb = replace_definitions(nb, params, *execute=False*,
lang='python3')

    ep = ExecutePreprocessor()
    ep.timeout = 3000
    new_nb, resources = ep.preprocess(new_nb, resources={})

Any idea if there is a way to pass timeout value to replace_definitions
somehow?

Appreciate any feedback.
Irek

**Comment by takluyver** [comment]
That's the best way to do it at present. We could expose extra options in `replace_definitions`, but I think it's fine to do it like that.

**Comment by IrekRybark** [comment]
Wow!  You are fast responding!

Thanks for the confirmation.
I was afraid that I missed something.

Good luck!
Irek

**Pull request merged**
