### PR TITLE
Converted to pip installable package

### PR DESCRIPTION
**Pull request by mt-krainski**
Hey,

As I've found this tool very useful, I've converted it to a normal Python package (so it can be installed in the system using pip). It required me to change a bit how the modules are internally loaded (in the `code.py` file). The `code.py` file is still getting the currently active kernel name, but now if the kernel name doesn't have a 'code_driver' defined (the corresponding `.py` file in the `code_driver` directory is not found), it's using just the python version (either `python2` or `python3`). It's useful if someone is using various different Python kernels and doesn't want to create a new 'code_driver' or rename stuff for every one of them.

Feel free to merge those changes if you deem them useful. But take care as I didn't change your tests or examples. I've just checked if it works for my [example](https://github.com/mt-krainski/ReportGenerationToolExample).

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! It's actually already pip installable [from PyPI](https://pypi.org/project/nbparameterise/) (`pip install nbparameterise`). It's not pip installable directly from the repository because I used [flit](http://flit.readthedocs.io/en/latest/) for packaging. If you need to install the development version, you can install flit and then use `flit install` to install from the repository.

I think it's a good idea to default to Python. I'd also like to switch it to using the language name in the notebook metadata; the original idea was that the kernel name would basically just be the language name, but that didn't work out in practice.

**Comment by takluyver** [comment]
I think it can be done without listing all the files in the directory, so I might close this PR and do it a bit differently, but thanks for tackling it. It's good to know that nbparameterise is useful to someone.

**Comment by mt-krainski** [comment]
Oh, cool. I've missed the PyPi version.... Sorry for the trouble then. 

I'm working with many kernels for various projects so I need that defaulting to Python version. I'll be checking from time to time to see if it's updated then.

**Comment by takluyver** [comment]
No problem. :-) I'll hopefully be able to do an update in the next couple of days.

**Comment by takluyver** [comment]
I've just pushed a change on master (5bf972900927bb8b36edb1f2e558d4d0436fe0ac) - can you test and see if that does what you want before I release?

**Comment by mt-krainski** [comment]
Yes, looks like it works perfect. Great! Thank You!

**Comment by takluyver** [comment]
Great. I'll probably do a release tomorrow. I want to try to think of another example notebook, because the 'Stock display' one isn't working very well at the moment.

**Comment by takluyver** [comment]
I've just published 0.3 to PyPI.

**Pull request closed without merging**
