### PR TITLE
replace % commands by comment

### LINKED ISSUE #9: Syntax error on % commands
If my notebook contains something like %matplotlib notebook in the first cell, we get an ugly failure:
```
File "/opt/conda/lib/python3.6/site-packages/nbparameterise/code.py", line 50, in extract_parameters
        params = list(drv.extract_definitions(first_code_cell(nb).source))
      File "/opt/conda/lib/python3.6/site-packages/nbparameterise/code_drivers/python.py", line 29, in extract_definitions
        cell_ast = ast.parse(cell)
      File "/opt/conda/lib/python3.6/ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 2
        %matplotlib notebook
        ^
    SyntaxError: invalid syntax
```

Maybe we could just remove these lines before sending them to parsing, what do you think?

### PR DESCRIPTION
**Pull request by JPMoresmau**
Fixes #9 

Not being a Python expert, I don't know if it's possible to have nice inheritance between tests (all my attempts have caused tests to be run in duplicate), so I've just copied and pasted the test. Let me know if the PR is OK.

### CODE REVIEW

**Comment by takluyver** [comment]
Really belated reply, sorry about this.

I'm reluctant to just regex out IPython magic commands, because a `%` at the start of a line is not automatically invalid Python (it can't be at the start of a statement, but a statement can spread over several lines). I've worked on how IPython actually recognises its own magic commands, and... it's complicated. I'd really rather not bring it into nbparameterise, which is pretty simple.

My thinking with nbparameterise is that you have a dedicated cell for parameters, before you do any imports or setup, so it's not important for it to handle IPython magics. I recognise not everyone wants to do it like that, but I'm never going to please everyone.

Is having to put the parameters first inconvenient? Maybe we should allow a cell tag or something to mark 'this is the parameter cell', and fall back on the first cell if it's not found.

**Comment by takluyver** [comment]
Also, I just remembered: `replace_definitions` will construct the new assignments, and then replace the entire cell. So any code in that cell other than assignments is effectively removed. It's not impossible to replace only the assignments, but it would make things significantly more complicated, in a direction that's not really important to me.

**Comment by JPMoresmau** [comment]
OK, no worries, it's not critical for me at the moment anyway.

**Comment by takluyver** [comment]
OK, thanks :-)

**Pull request closed without merging**
