### PR TITLE
Timeout parameter added in the ExecutePreprocessor

### PR DESCRIPTION
**Pull request by nurullah**
30 seconds is not enough to execute notebooks. The documentation recommends 600 seconds.

https://nbconvert.readthedocs.io/en/latest/execute_api.html#example

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, but I'm not going to change anything about execution in nbparameterise now - I strongly encourage executing the notebook as a separate step after using nbparameterise, giving you full control over how it's executed, rather than getting nbparameterise to do it. The `execute=` option will probably go away one day (unless I'm too lazy :wink: )

**Comment by nurullah** [comment]
I would not recommend remove the execute parameter. Because user do not need to include the nbconvert library in their application for the executing. Because you already provide them as a feature. I think this is a good thing.

**Comment by takluyver** [comment]
They still get nbconvert as an indirect dependency, though.

**Comment by takluyver** [comment]
Thanks for the contribution, but I'm going to close this for the reasons discussed above. If you want execution, please substitute the parameters and then call nbconvert - or the newer [nbclient](https://nbclient.readthedocs.io/en/latest/client.html) package - separately to execute the notebook, giving you lots of options relating to execution.

**Pull request closed without merging**
